version: '3'

volumes:
  appdata:
  db:

services:
  nginx:
    image: nginx:latest
    env_file: .env.docker.dev
    ports:
      - 8090:80
    volumes:
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - appdata:/var/www/var/log
      - appdata:/var/www/var/cache
      - .:/var/www:cached
    depends_on:
      - php

  php:
    build:
      dockerfile: docker/dev/php/Dockerfile
      context: .
    env_file: .env.docker.dev
    volumes:
      - appdata:/var/www/var/log
      - appdata:/var/www/var/cache
      - .:/var/www:cached

  db:
    image: mariadb:10.4
    volumes:
      - db:/var/lib/mysql:rw
    ports:
      - "8091:3306"
    expose:
       - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8092:80"
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=dev
      - PMA_PASSWORD=dev




